name: Django CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run tests
      run: |
        cd web_app_test
        python manage.py test
    
    - name: Build Docker image
      run: docker build -t django-practice .
    
    - name: Run Docker container
      run: |
        docker run -d -p 8000:8000 --name django-app django-practice
        sleep 10  # Wait for the server to start
        curl http://localhost:8000/apiviews/info/  # Test the API endpoint 